# Generated by Django 4.0.1 on 2022-01-12 14:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_minuses_target_pros'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
