# Generated by Django 4.0.1 on 2022-01-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_target_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
